### PR TITLE
Sort controller Unit Test Coverage #492

### PR DESCRIPTION
**Pull request by rsknutson**
Unit test for sort-controller

### CODE REVIEW

**Comment by bharney0** [comment]
@rsknutson we have changed the root directory to contain a `packages` folder where all of the extensions live. Can make sure the changes are made in `packages/docs-markdown` folder? So your new path would be `packages/docs-markdown/src/test/suite/controllers/sort-controller.test.ts`

**Comment by rsknutson** [comment]
Opened new PR

**Pull request closed without merging**
