### PR TITLE
Added Moniker to quick-pick-menu-controller.ts

### PR DESCRIPTION
**Pull request by JohnTheFarmer**
solved #546   &&  added unit test coverage: code-controller

### CODE REVIEW

**Comment by jamarw** [comment]
Thanks @JohnTheFarmer , thanks for the contribution!  We'll review the PR soon and let you know if there's any feedback.

**Comment by jamarw** [comment]
Hi @JohnTheFarmer , the code/functionality look great!

@meganbradley @bharney0 @adunndevster Do you think we should add context validation to the moniker command? AFAIK the attribute should only apply to the YAML header so should we add a context check to ensure the cursor is in the header and if it's not we bail on the command and notify the user?

**Comment by JohnTheFarmer** [comment]
@jamarw I believe it also applies to the markdown body. #362

**Comment by jamarw** [comment]
> @jamarw I believe it also applies to the markdown body. #362

Hey @JohnTheFarmer , looks good!  It seems like it was adding the attribute to the markdown body when I first tested but it could've just been me.  I'll approve the PR and we'll ship the update soon.

Thanks

**Comment by JohnTheFarmer** [comment]
@jamarw I also added unit test coverage for code-controller and made some other simple changes, please review

**Comment by bharney0** [comment]
@JohnTheFarmer  Thank you again for your contributions. We expect to release these changes to production tomorrow on docs-markdown release version `0.2.67`

**Pull request merged**
