### PR TITLE
Added Link to Docs Page by URL to quick pick menu

### PR DESCRIPTION
**Pull request by bharney0**
Added function that either tries to find the local file in the repo or converts the url to a relative path. Functionality was added to links quick pick menu. Additionally, the option was added to Link to Web page and if the URL is a docs.microsoft.com link there will be a submenu offering to convert the link to a relative URL with the local file if its in the repo, or relative path if its not in the repo.
 - Link to Docs Page by URL added to Links quick pick menu.
   - If link is in current repo then point to the local file.
   - If not in local repo then shorten URL to be relative to docs site.
- Added submenu to Link to web page for adding ability to convert link to call Docs Page by URL

[AB#374305](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/374305)
[AB#374304](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/374304)
[AB#376941](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/376941)
[AB#193989](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/193989)

PR also fixes issue found with docs-article-template vscode typing when doing pre-push command with husky causing linting to fail on push.

### CODE REVIEW

**Review by lamebrain — COMMENTED** [review]
Can you add tests for `linkToDocsPageByUrl.ts`

**Comment by bharney0** [comment]
@lamebrain I added a few unit tests to the PR. Please review.

**Comment by lamebrain** [comment]
@bharney0 

Couple failed cases:

(in local folder azure-docs-pr)
> Link to Docs page by URL
> entered: https://docs.microsoft.com/en-us/azure/app-service/overview
> output: [app service overvie](../app-service/overview.md)
^ should be "app service overview"

(in local folder azure-docs-pr)
> Link to Docs page by URL
> enter: https://docs.microsoft.com/en-us/microsoft-365/solutions/empower-people-to-work-remotasdfasdfely?view=o365-worldwide
nothing happens, should get a message that the url is invalid?

**Comment by bharney0** [comment]
@lamebrain good catch on those issues. I fixed the problems with both local folder for azure-docs-pr case removing the ending character, and instances where the request returns a 404.

**Review by lamebrain — APPROVED** [review]

**Pull request merged**
