### PR TITLE
Removed unsupported dev langs.

### PR DESCRIPTION
**Pull request by bharney0**
[Task](https://dev.azure.com/ceapex/Engineering/_boards/board/t/AXE%20Team/Stories/?workitem=181630) for removing unsupported languages from ``` auto complete.

### CODE REVIEW

**Comment by IEvangelist** [comment]
Hi @bharney0,

This is actually incorrect now and will introduce issues. The list that was provided in the task is incorrect and missing languages that are actually supported. For example, at a glance you're removing all the valid interactive dev langs. Every single interactive dev lang that was listed is actually fully supported by the platform. Let's have a discussion before this change is merged, please.

**Comment by bharney0** [comment]
@IEvangelist I agree. We should have more of a discussion about what languages can be removed before doing anything. At this point, its not a big deal if there are more languages, the user can always search in the list. @meganbradley @adunndevster @jamarw

**Comment by bharney0** [comment]
@IEvangelist as per @adkinn advice, we should use our current taxonomy that is supported by the system and not the list in the highlightjs code. If devlangs should be added to the list we can make requests to the IA team.

@adunndevster Should I go ahead and merge this?

**Comment by IEvangelist** [comment]
> @IEvangelist as per @adkinn advice, we should use our current taxonomy that is supported by the system and not the list in the highlightjs code. If devlangs should be added to the list we can make requests to the IA team.
> 
> @adunndevster Should I go ahead and merge this?

I'm sorry, but @adkinn is incorrect. The platform supports interactive, and you're removing that. Which is wrong.

**Comment by adkinn** [comment]
@IEvangelist that's such a sweeping statement. It's not incorrect to remove all of the devlangs not in our taxonomy. Keeping the interactive modifier is not a bad idea.

@bharney0 I think it makes sense to maintain the "interactive" modifier tags. Let's keep those and remove the rest.  Additionally we can update our taxonomy script to output this list when we make changes on the source of truth.

**Comment by IEvangelist** [comment]
Hi @adkinn and @bharney0,

## In production today

Call me customer-obsessed... but, there are other languages being removed that **are in fact supported**, besides just the interactive ones the taxonomy list that you have is still incomplete. At a glance, I initially noticed that the interactive ones were missing - I happy I looked deeper.

For example, in production today on the [docs.microsoft.com/azure](https://docs.microsoft.com/en-us/azure/) site we're using the following dev langs, that you're attempting to remove (however, these are work correctly):

| Dev Lang | Link(s) | Image from PROD |
|------------|------|-----|
| `apache`, `apacheconf` | [1](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-troubleshoot-hive#resolution-steps), [2](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-troubleshoot-yarn#resolution-steps-1) | image |
| `gradle` | [1](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-how-to-use-client-library#gradle-build), [2](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-tutorial-create-java-app), [3](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-users) | image |
| `groovy`   | [1](https://docs.microsoft.com/en-us/azure/jenkins/tutorial-jenkins-deploy-cli-spring-cloud-service#create-a-jenkinsfile), [2](https://docs.microsoft.com/en-us/azure/jenkins/tutorial-jenkins-deploy-cli-spring-cloud-service#create-a-jenkinsfile), [3](https://docs.microsoft.com/en-us/azure/jenkins/jenkins-aks-blue-green-deployment#edit-the-jenkinsfile) | image |
| `kotlin` | [1](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/java-sdk), [2](https://docs.microsoft.com/en-us/azure/cognitive-services/bing-visual-search/visual-search-sdk-java#create-a-new-gradle-project), [3](https://docs.microsoft.com/en-us/azure/cognitive-services/content-moderator/java-sdk-quickstart) | image |
| `ini` | [1](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-benchmarks#maximum-write-iops), [2](https://docs.microsoft.com/en-us/azure/site-recovery/physical-manage-configuration-server#create-file-input-for-mysqlcredsfilepath), [3](https://docs.microsoft.com/en-us/azure/jenkins/tutorial-jenkins-deploy-web-app-azure-app-service#create-jenkins-pipeline) | image |
| `nginx` | [1](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1#configure-nginx) | image |
| `properties` | [1](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-kafka-connect-tutorial#configure-kafka-connect-for-event-hubs), [2](https://docs.microsoft.com/en-us/azure/app-service/containers/tutorial-java-spring-cosmosdb) | image |
| `terraform`, `tf`, `hcl`, | [1](https://docs.microsoft.com/en-us/azure/terraform/terraform-backend), [2](https://docs.microsoft.com/en-us/azure/terraform/terraform-create-complete-vm) | image |

Other dev langs that are in the wild today, that I was too lazy to dig up the proof of their existence / usage -- but trust me they are being used and correctly syntax highlight.

* **PostgreSQL & PL/pgSQL**: `pgsql`, `postgres`, `postgresql`
* **Shell**: `shell`, `console` (actually we need to discuss this one)


## Plaintext

Please leave this one too, as it is a unified way of communicating a desire for a code-fence to have structured text - but no highlighting.

| Name | Dev lang |
|--------|-----------|
| Plaintext no highlight | `plaintext` |

## Interactive dev langs

| Name | Dev lang |
|--------|-----------|
| Azure CLI (Interactive) | `azurecli-interactive` |
| Azure PowerShell (Interactive) | `azurepowershell-interactive` |
| C# (Interactive) | `csharp-interactive` | 
| MS Graph (Interactive) | `msgraph-interactive` |
| PowerShell (Interactive) | `powershell-interactive` |

**Comment by scottaddie** [comment]
My opinion is that there should be a small group discussion about this PR before merging. In quickly scanning through the list of dev langs to be removed, I noticed a handful that my team uses. It's an impactful change that's likely to affect many other content developers.

**Comment by adkinn** [comment]
@IEvangelist @scottaddie yes they are many languages that are not in our taxonomy yet. This PR will not remove support for this languages.

This PR is an effort to reconcile our linting hints with our taxonomy. We can add new devlangs to the taxonomy to update it in the future.

**Comment by DuncanmaMSFT** [comment]
FYI folks, as long as we are open to adding more languages to the taxonomy (as per Adam: "We can add new devlangs to the taxonomy to update it in the future."), then this change doesn't break anybody. I saw my name used at the beginning, and was going to say that the correct guidance of supported languages is https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master#supported-languages **but** someone has added to that list and made it inaccurate. For example, we don't want people using both cs and csharp for C#, only csharp for consistency. In many cases, just because an alias is supported in highlight.js, we won't change that into the proper friendly name and we'll end up with an inconsistent user experience. Also, just because a language is *in* highlight.js doesn't mean it is **supported**. It will work, but if decide at some point to change our highlighting provider it may not. That list should be the languages that are actively being used on Docs, with the chosen single alias, not just a dump of every language from a specific open source highlighting project.

**Comment by IEvangelist** [comment]
Hi @DuncanmaMSFT,

Thank you for speaking up, you said:

> then this change doesn't break anybody

Let me explain how this does in fact break consumers. Removing certain things from the statement completion list will cause warnings for developers, who are using identifiers not in this list (false negatives) and the tool will instruct them to change the dev lang, as it would then be unrecognized. Thus, making this a breaking change. If we have code snippets that show `nginx` for example, and it has the correct syntax highlighting... it is valid. Removing it from the list, will cause issues and confuse users of the DAP extension.

If the platform supports, we want to guide the content developers (and external contributors) down a path of success and show them what valid options are available to them. I hear you, that we can update one of the several, master lists but we need alignment on what the list is. I've been asking multiple folks for this information for a while now, and decided to take action.

> That list should be the languages that are actively being used on Docs, with the chosen single alias, not just a dump of every language from a specific open source highlighting project.

I agree that we shouldn't just dump every language that is supported by highlightjs into the docs, but what is the appropriate list -- have you ran audits on docsets, do you know all the dev langs? I have done this on the Azure repo and know what is being used, several of which this PR is trying to remove.

> For example, we don't want people using both cs and csharp for C#, only csharp for consistency.

I agree, the tool today works with `csharp` but it will not warn people who are using `cs` as it is technically valid and they both render the exact same, i.e.; the syntax highlighting is accurate and the label is `C#`. The first alias is used by the tool when inserting a dev lang, the other aliases are then to ensure that a dev lang is not invalid. I too want consistency and this tool gets us much closer to having that.

**Comment by bharney0** [comment]
@DuncanmaMSFT @adkinn @IEvangelist @scottaddie 13 languages have been added back to the list which includes the 8 being used in azure docs, in addition to the 5 interactive ones. Let me know when we have a more comprehensive list so we can get it updated.

**Comment by IEvangelist** [comment]
This looks good, thank you @bharney0!

You'll need to also update the `package.json` to correct the schema to reflect these changes. Unfortunately the JSON schema is still a separate list for now. [See here](https://github.com/microsoft/vscode-docs-authoring/blob/master/docs-markdown/package.json#L473-L684). After that is done and when this gets pushed out, several docset repos will have to correct their local `settings.json` file to match the names for their workspace scoped `makrdown.docsetLanguages`. /cc @scottaddie FYI about this last point...

**Comment by bharney0** [comment]
> This looks good, thank you @bharney0!
> 
> You'll need to also update the `package.json` to correct the schema to reflect these changes. Unfortunately the JSON schema is still a separate list for now. [See here](https://github.com/microsoft/vscode-docs-authoring/blob/master/docs-markdown/package.json#L473-L684). After that is done and when this gets pushed out, several docset repos will have to correct their local `settings.json` file to match the names for their workspace scoped `makrdown.docsetLanguages`. /cc @scottaddie FYI about this last point...

Thanks for letting me know. I've updated the package.json as well.

**Comment by scottaddie** [comment]
Heads up that our C++ docs do use both the ARM assembler and Makefile dev langs. Are we sure those should be removed? See https://github.com/MicrosoftDocs/cpp-docs/blob/ef8836e9deb10f0b18ac1d4d043cb65ae0e51735/.vscode/settings.json#L6-L16.

**Comment by bharney0** [comment]
@scottaddie I'm fine with including those since they are being used in C++ docs, @adkinn any objection?

**Pull request merged**
