### PR TITLE
Add Metadata tree view contextual to docfx markdown files

### PR DESCRIPTION
**Pull request by IEvangelist**
Hi friends!

Tagging for visibility: @meganbradley @bharney @adunndevster @jamarw and @lamebrain

Genevieve (@gewarren) was leading a [hackathon effort](https://garagehackbox.azurewebsites.net/hackathons/2333/projects/101127) that I was helping contribute to.

> This Visual Studio Code extension will dynamically show the effective metadata for the article that's open in the editor. For example, some metadata is applied globally or per-folder in the _docfx.json_ file.

## In this PR

We're adding a **Metadata** tree view to the side bar. There is a welcome message shown when it's first loading, or when empty. Navigating to a MD file will show the tree view contents. The tree view is categorized based on **Required** and **Optional** metadata. The Optional metadata node is collapsed by default while the **Required** is expanded by default.

The rules of precedence are imposed that align with DocFX implementation, for example: Front matter > File Metadata > Global Metadata. 

### Icons

Icons are used as hints to the source in which metadata is going to be applied.

- Red alert icon: when missing required metadata is discovered
- Yellow JSON icon: when metadata is from the `build/fileMetadata` section of the _docfx.json_ file
- Cyan globe icon: when metadata is from the `build/globalMetadata` section of the _docfx.json_ file
- Blue markdown icon: when metadata is from the front matter YAML of the MD file

### Details

- Update _settings.json_ to correctly specify the default formatter
- Add SVG image assets for new tree view icons
- Add refresh tree view command
- Add welcome screen to empty tree view
- Add new tree view for a MD files metadata
- Rely on `minimatch` package to perform comparison of file globs without hitting the file system (non-I/O)
- Move `metadata-controller.ts` to new _metadata_ directory
- Added the ability to find, read/parse, and cache the _docfx.json_ file
- Added the ability to parse, and interpret a MD files "effective" metadata based on the _docfx.json_ file
- Add/register new `TreeViewProvider` implementation _metadata-tree-provider.ts_
- Clean up _common.ts_ imports
- Added the ability to traverse directories searching for a file (avoids scoping issue with files outside the workspace)
- Added and clean up unit tests

## Future work

We'd like to add the ability to make the tree items clickable, and then navigate to the line in the file where it was discovered:

- Line number of the glob pattern from the `build/fileMetadata` section of the _docfx.json_ file
- Line number of the value from the `build/globalMetadata` section of the _docfx.json_ file
- Or the current MD file's YAML front matter

## Limitations

When you have **Files > Auto Save** enabled (anything other than `off`), you'll have to manually **Refresh** the tree view after the file is saved. This is due to a limitation with our ability to detect file saves and automatically refreshing of the tree. In other words, when auto save is on, it's a performance drain on the IDE as the tree is updating more often than needed.

When **Files > Auto Save** is set to `off`, this automatically updates the tree view.

## Known issues

As of right now 11:22 AM CDT, June 9th 2021 - when looking at an include file - it will report missing required metadata. We'll need to update this to consider "include" files as something that has a different set of required metadata.

## In action

Example article
image
Example hover
image
Front matter, `fileMetadata`, `globalMetadata` example
image
Missing example
image

### CODE REVIEW

**Comment by lamebrain** [comment]
This is great! We'll get this reviewed soon. Thanks

**Review by bharney0 — APPROVED** [review]
@IEvangelist This seems to work great! I would be nice to automatically refresh the metadata panel when updating the metadata on a markdown file. But this is awesome! Great work.

**Comment by IEvangelist** [comment]
> @IEvangelist This seems to work great! I would be nice to automatically refresh the metadata panel when updating the metadata on a markdown file. But this is awesome! Great work.

This was @gewarren's idea, hackathon project - I just helped out! She deserves all the credit. As for the auto-refresh, this is a known limitation and we call attention to it in the **Limitations** above.

**Pull request merged**
