### PR TITLE
Removed Spell Checker from list of depedencies and added as recommend…

### PR DESCRIPTION
**Pull request by bharney-msft**
…ation.

### CODE REVIEW

**Comment by nschonni** [comment]
Won't this just recommend it for people editing this workspace not other repos?

**Comment by nschonni** [comment]
Is there a reason you're dropping this? It's found quite a few docs and product issues in the docs

**Comment by bharney-msft** [comment]
> Is there a reason you're dropping this? It's found quite a few docs and product issues in the docs

I believe the rational was because the spellchecker could not be disabled when it is set as dependency. And had been displaying linting warnings in code, but no way to turn the warnings off.

**Comment by nschonni** [comment]
It can be disabled for a project/workspace by adding `"cSpell.enabled": false` in the settings.json.
That is what the menu item `Disable Spell Checking For Workspace" does, although I recognize that isn't the same as disabling the plug-in fully

**Comment by nschonni** [comment]
Looks like the `"cSpell.enabled": false` works at the global VS Code settings.json to turn it off for all projects

**Pull request closed without merging**
