### PR TITLE
Escape xref syntax to display plain text

### PR DESCRIPTION
**Pull request by qinezh**
#83

### CODE REVIEW

**Comment by qinezh** [comment]
@jamarw Can you please take a look about it? Thanks~

**Comment by qinezh** [comment]
@adkinn and @meganbradley Is there anyone else available to take a look at my PRs? Thanks in advance~

**Comment by jamarw** [comment]
Hi @qinezh , sorry I must've missed the GH notification.  I'm reviewing the open PR's now.  Thanks

**Comment by meganbradley** [comment]
@jamarw let me know when there's a new build for me to test. :)

Thanks @qinezh !

**Comment by qinezh** [comment]
Thanks @jamarw 😄

**Comment by qinezh** [comment]
@meganbradley a new version of docs-preview has been released. Please have a try~

**Pull request merged**
