### PR TITLE
Visual areas

### PR DESCRIPTION
**Pull request by johnpapa**
Creating pull request to add the docs-visual-areas extension as a new extension to be published as part of the authoring pack.

Consistency checks

- [x] followed overall consistency of the rest of the packages 
- [x] followed same eslint, except index.ts usage
- [x] followed same prettier
- [x] followed same webpack 
- [x] followed same script usage
- [x] updated root package.json file for lint and compile steps

Visual Areas:

docs-visual-areas-demo

Easily keep track tabbed and zoned content with the following features:

- **Color coded gutters**: Each tabbed or zoned section in your article gets a unique gutter color.

- **Area tooltips**: Hovering over a line in a section reveals a tool tip with the area label.

- **Status bar**: The status bar stays updated with the section name when your cursor is inside a tabbed or zoned section.

## Demo video

[Demo video](https://www.youtube.com/watch?v=LXLqH-MEH6o)

## Settings

| Property               | Description                                        | Default |
| ---------------------- | -------------------------------------------------- | ------- |
| gutterIndicatorHeight  | The height the of gutter indicator.                | 100     |
| gutterIndicatorOffset  | The offset from the left for the gutter indicator. | 12      |
| gutterIndicatorOpacity | The opacity percentage of the gutter indicator.    | 60      |
| gutterIndicatorWidth   | The width the of gutter indicator.                 | 4       |

cc @craigshoemaker @kgremban @IEvangelist

### CODE REVIEW

**Comment by IEvangelist** [comment]
Awesome, thank you @johnpapa! Hey @bharney0 - we need a CI run.

**Comment by bharney0** [comment]
@meganbradley can you review the description in this PR for getting the OK on adding this new extension to the Docs Authoring Pack? 

Thank you @johnpapa for your contribution! Im working on reviewing the code and once that is setup I will need to create a CI pipeline for publishing to the VSCode Marketplace and future changes.

**Comment by lamebrain** [comment]
This looks great @johnpapa! We're currently under water at the moment, but we'll get this reviewed as soon as we can.

**Review by bharney0 — COMMENTED** [review]
Hey @johnpapa thanks again for the contribution. Just getting around to this. Sorry for the delay. Future PRs should be reviewed within a few days. Our Org was involved in a security audit which put a hold on other work. A few things I noticed from the code:

- Can you remove the .DS_Store folder
- Please avoid upper case file names for the test data

Overall the code looks well put together, however when I try to use the extension in the extension host I dont see the visual areas? Is there something I am doing wrong?
image

**Comment by johnpapa** [comment]
> Hey @johnpapa thanks again for the contribution. Just getting around to this. Sorry for the delay. Future PRs should be reviewed within a few days. Our Org was involved in a security audit which put a hold on other work. A few things I noticed from the code:
> 
> * Can you remove the .DS_Store folder
> * Please avoid upper case file names for the test data
> 
> Overall the code looks well put together, however when I try to use the extension in the extension host I dont see the visual areas? Is there something I am doing wrong?
> image
> 
> As far as next steps, I built a CI pipeline and need to run it under main branch for component governance checks and CodeQL analysis. I Just need to setup a CD pipeline to deploy under the Microsoft VS Marketplace.

Hi - thanks for the feedback, I will review this and reply soon.

**Comment by johnpapa** [comment]
@bharney0 - I made the fixes you requested to the PR and pushed them up.

I tried the extension locally and it worked for me (see below). Perhaps you are trying it on a file that is not an *.md ? 

image

**Comment by bharney0** [comment]
Hey @johnpapa this is the error I run into when I try to run the Extension Host
image

I also tried packaging it up into a .vsix for @meganbradley to test out but I am still getting the same error.

image

Let me know if I can help in any way, I would love to get this deployed to the authoring pack and get some more downloads.

Also can you resolve the package-lock.json conflict or even remove the package-lock so I can test the CI build pipeline to make sure we dont have any component governance issues?

**Comment by bharney0** [comment]
@johnpapa I just changed some configuration settings in the .vscode file for tasks and launch.json files and updated the output directory for main in the package.json and everything seems to be working now. 

image

I am going to send over a .vsix file for our PM to check out the extension and then merge it into main so we can get a build to check for component governance and security related code analysis. Then we should be able to publish to the market place. Thanks again for your patience. Hopefully in the future with other PRs we will be quicker to get things moving.

**Review by bharney0 — APPROVED** [review]

**Comment by johnpapa** [comment]
Thanks @bharney0. I am OOO til tomorrow, so I appreciate you keeping this moving forward.

I tried to mirror the extension after some of the others I saw in this repo, but I agree that some contribution guidelines and checklists may be incredibly helpful for future contributions.

No worries on the time this took. Y’all have been communicative and I understand my PR has to follow your structure. Thanks for considering this PR.

Let me know if there is anything else.

**Pull request merged**
