### PR TITLE
Fix multiple top level headings lint error

### PR DESCRIPTION
**Pull request by jamarw**
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md025---multiple-top-level-headings-in-the-same-document

### CODE REVIEW

**Comment by jamarw** [comment]
Closing existing [PR](https://github.com/microsoft/vscode-docs-authoring/pull/273) that was based off develop branch.

**Comment by nschonni** [comment]
Can you detect that you're running on a MS Docs project by sniffing for the openbuild or something?
This still has the problem of affecting users of the plugin whether or not their working on MS Docs projects

**Comment by nschonni** [comment]
PS: I also dislike how they changed this setting, i just don't think you should override the config for all projects

**Comment by jamarw** [comment]
> Can you detect that you're running on a MS Docs project by sniffing for the openbuild or something?
> This still has the problem of affecting users of the plugin whether or not their working on MS Docs projects

Hi @nschonni , good point.  Unfortunately, the setting will be added once the user opens a docs repo so the sniffing wouldn't completely solve the problem.  We'd like to remove the setting on close if the user did not set it explicitly but the deactivation process runs quickly and doesn't allow enough time to launch the reset.  A setting has been added that will allow users to disable the automated parameter setting if they'd like.  Thanks for the feedback.

**Comment by nschonni** [comment]
Thanks!
One other though, if the repo has a .markdownlint.json file, they can update the config to match this. If they don't have a .markdownlint.json in the repo, there are a lot more issues that markdownlint will flag besides MD025 in a normal repo.
MD025 will also still be flagged for repos that use the "tabs" (even if that is discouraged) because they tend to use H1s in their format as well.

**Comment by nschonni** [comment]
I've slowly been PRing `.markdownlint.json` files, but it's hit and miss as to which repos accept them 😉

**Pull request merged**
